import './globals.css';
import type { Metadata } from 'next';
import { ActivityBar, BottomBar, CollapsableMenu, TopBar } from '@/components';
import { Providers } from '@/lib/providers';
import TogglePortfolio from '@/components/TogglePortfolio';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body className={`bg-dark_bg min-h-screen flex flex-col`}>
          <TopBar />
          <div className="flex-1 flex">
            <ActivityBar />
            <CollapsableMenu />
          </div>
          {children}
          <BottomBar />
          <TogglePortfolio />
        </body>
      </html>
    </Providers>
  );
}
